apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-srv-smoke
  namespace: storage-smoke
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-srv
  resources:
    requests:
      storage: 64Mi
